disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- line_length
- force_cast
- identifier_name
- legacy_constructor
- type_body_length
- file_length
- notification_center_detachment
- multiple_closures_with_trailing_closure
- nesting
- cyclomatic_complexity
- function_body_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
